import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const space = localFont({
  src: "./font/SpaceGrotesk-Variable.ttf",
  variable: "--font-geist-sans",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${space.className}  antialiased`}>{children}</body>
    </html>
  );
}
